### ISSUE TITLE
Could not install the package using pip 1.3.1

### ISSUE THREAD

**Issue by DeepthiGaddam** [taykey/python-kafka-logging#11]
error: 
Running setup.py egg_info for package python-kafka-logging
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/python-kafka-logging/setup.py", line 23, in <module>
        install_requirements = parse_requirements('requirements.txt', None, None, None, uuid.uuid1())
    TypeError: parse_requirements() takes at most 4 arguments (5 given)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

**Comment by avihoo** [comment]
Hi,

Did you try to update your pip client to the newest version?
Try to update your pip client using: `sudo pip install --upgrade pip`

Let me know if works.

**Comment by avihoo** [comment]
Closing due to lack of response. If needed, will reopen.
